### ISSUE TITLE
Symmetric lesions - asymmetric disconnectivity metrics

### ISSUE THREAD

**Issue by m-petersen** [jdwor/LQT#7]
Dear Jordan,

thanks for porting the LQT to R.

I am interested in tract-wise disconnectivity metrics of white matter hyperintensities of presumed vascular origin (WMH) in two normal population samples. Therefore, I input WMH masks in MNI in LQT according to your tutorials and extract disconnectivity indices from the .csv in Tract_Disconnetion directories. However, I have encountered a problem while deriving disconnectivity metrics with your toolbox.

WMH occur relatively symmetric as can be seen in the example visualization below which show the input lesion segmentations (1mm) overlayed on a T1 in MNI.
![wmh_in_mni0001](https://user-images.githubusercontent.com/39294105/228241136-9dbc72f0-bf20-44bf-a545-106361c30661.png)
![wmh_in_mni0002](https://user-images.githubusercontent.com/39294105/228241116-cf881a85-e231-4123-b91c-3a4d6d805ad1.png)

However, when I plot the tract-wise disconnectivity indices against age the indices appear to be relevantly asymmetric, i.e., differ between bilateral tracts. This applies to most tracts I have looked into.
![centiles_1](https://user-images.githubusercontent.com/39294105/228250285-6ab0153e-f19e-47e5-9df7-bc0243014570.png)
![centiles_1](https://user-images.githubusercontent.com/39294105/228250350-f08df5d5-b197-4582-b419-6767f98e36b7.png)

I assume asymmetries are possible, however, to that degree it is somewhat unexpected. Do you have an idea what might cause that? Thanks in advance for any help. Happy to provide further information if needed.

Best,
Marvin

**Comment by jdwor** [comment]
Hi Marvin, thanks for your note! I unfortunately left academia a few months ago and am unable to continue actively maintaining this package. I recommend looking into Amy Kuceyeski's NeMo tool as an alternative (https://github.com/kjamison/nemo)

Regarding your question - that does seem strange, and since I've never done any explicit LH/RH comparisons I can't tell whether it's new and weird or has always been the case. I will say that I think the tracts themselves are sometimes quite asymmetric in size and/or location, so it could be that AF_L is bigger or positioned more periventricularly. Hard to say for sure, but that's where I would start the investigation if I were you.

**Comment by m-petersen** [comment]
Thanks for your prompt answer and recommendations, Jordan! I solved the issue by using a DSI studio version that fits my Ubuntu Version (20.04). Beforehand I used that for 16.04. Now I get more plausible disconnectivity metrics. I'll also take a look into the NeMo toolbox.
